{% set name = "dttxml" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dttxml-{{ version }}.tar.gz
  sha256: abc71df2386acac6eb07b06d6dba83e87cc5da52b9c000fa93357f9b5ab5d6db

build:
  number: 1
  noarch: python
  entry_points:
    - dtt2hdf = dttxml.dtt2hdf:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - declarative >=1.3.0
    - h5py
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - dttxml
  requires:
    - matplotlib-base
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - conftest.py
    - test/
  commands:
    # check requirements
    - python -m pip check
    # run tests
    - python -m pytest -ra -v test/
    # sanity check the entry points
    - dtt2hdf --help

about:
  home: https://git.ligo.org/cds/dttxml
  doc_url: https://cds.docs.ligo.org/dttxml/
  dev_url: https://git.ligo.org/cds/dttxml.git
  summary: Extract data from LIGO Diagnostics test tools XML format
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Utilities for extracting data from LIGO Diagnostics Test Tools xml format.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - evonreis
